// <auto-generated />
using System;
using LifeHub.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LifeHub.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260402173405_AddCreativeSpacesAndVersioning")]
    partial class AddCreativeSpacesAndVersioning
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // ...existing code...
        }
    }
}
