FROM mcr.microsoft.com/dotnet/sdk:8.0

WORKDIR /app

# Instalar herramientas globales
RUN dotnet tool install --global dotnet-ef
ENV PATH="/root/.dotnet/tools:${PATH}"

# Copiar archivos del proyecto
COPY . .

# Restaurar dependencias (sin usar cache si hay cambios en .csproj)
RUN dotnet restore --no-cache

# Exponer puerto
EXPOSE 8080

# Ejecutar en modo desarrollo
CMD ["dotnet", "watch", "run", "--no-restore"]
